### ISSUE TITLE
Broken Permalink - points to wrong mailing list

### ISSUE THREAD

**Issue by sebbASF** [quenda/ponymail#41]
The list https://lists.apache.org/list.html?derby-dev@db.apache.org contains a message entitled "Document" dated May 12. View Source starts as follows:

Return-Path: <derby-dev-return-116554-archive-asf-public=cust-asf.ponee.io@db.apache.org>

However, click on "Permalink" and then use View Source, and one gets:

Return-Path: <infrastructure-issues-return-70997-archive-asf-public=cust-asf.ponee.io@apache.org>

The bodies of the mail are similar, but not identical.

I don't know if it's significant, but the email appears to contain a suspicious/malicious document.
Other derby-dev Permalinks I checked seemed to work OK.

**Comment by Humbedooh** [comment]
This is a compression issue in short links, where message IDs are shortened to make the permalink URL shorter. The correct email is found, but since the email (with the same message ID and body) has been sent to multiple lists, the backend returns with the first email that matches the message ID instead of matching both message ID and mailing list. 

This is configurable in config.js with the shortLinks boolean value. When turned off, the full message ID (including the target list ID) is used.

**Comment by sebbASF** [comment]
It's not the same e-mail.

The attachment is the same, and the messages are very similar, but they are not the same.

The messages have different Date: values and different boundary strings.

i.e. entirely the wrong email is found by the permalink, not just the wrong copy.

==

It seems to me that if the shortLink depends only on the body content (and none of the headers) then replies can easily be sent to the wrong list. If someone sends the same message separately to multiple lists, it sounds like the short links will be the same. So if the shortlink is used to select the message in order to Reply to it, the reply will go to the wrong list.

That's the case here; the original message was sent to derby-dev; the permalink message was sent to infrastructure-issues. So if I reply to the permalink it will go to the wrong list.
